server:
  port: 8081
spring:
  application:
    name: Log-A
  main:
    allow-bean-definition-overriding: true #spring boot2.1做了修改，解决多个Feign引用同一个服务地址的问题
  sleuth:
      web:
        client:
          enabled: true
      sampler:
        #默认的采样比率为0.1，不能看到所有请求数据
        #更改采样比率为1，就能看到所有的请求数据了，但是这样会增加接口调用延迟
        probability: 1.0
  profiles:
    active: pro
  zipkin:
      base-url: http://localhost:9411/ # 指定了 Zipkin 服务器的地址


eureka:
  client:         #客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 15000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
management:
  endpoint:
    health:
      show-details: always
    web:
      exposure:
        include: '*'
